// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfUJvjyNDtG9bjPMN-RjV_uceGbJ6JK28',
    appId: '1:719995247413:web:87f8dc6270f4543d944a7c',
    messagingSenderId: '719995247413',
    projectId: 'flutterunicodetask',
    authDomain: 'flutterunicodetask.firebaseapp.com',
    storageBucket: 'flutterunicodetask.firebasestorage.app',
    measurementId: 'G-LD44F48TXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIPkBR7lqziiutTBTwRoJJo340TbJQ5o',
    appId: '1:719995247413:android:5c342a84af30d962944a7c',
    messagingSenderId: '719995247413',
    projectId: 'flutterunicodetask',
    storageBucket: 'flutterunicodetask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjURCBZPZB_RSrJol9s1uF8DE-aRCbhQg',
    appId: '1:719995247413:ios:0c26a868fa05739d944a7c',
    messagingSenderId: '719995247413',
    projectId: 'flutterunicodetask',
    storageBucket: 'flutterunicodetask.firebasestorage.app',
    iosBundleId: 'com.example.movieReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjURCBZPZB_RSrJol9s1uF8DE-aRCbhQg',
    appId: '1:719995247413:ios:0c26a868fa05739d944a7c',
    messagingSenderId: '719995247413',
    projectId: 'flutterunicodetask',
    storageBucket: 'flutterunicodetask.firebasestorage.app',
    iosBundleId: 'com.example.movieReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfUJvjyNDtG9bjPMN-RjV_uceGbJ6JK28',
    appId: '1:719995247413:web:800f41268cc8b362944a7c',
    messagingSenderId: '719995247413',
    projectId: 'flutterunicodetask',
    authDomain: 'flutterunicodetask.firebaseapp.com',
    storageBucket: 'flutterunicodetask.firebasestorage.app',
    measurementId: 'G-445C4M6NRF',
  );

}